#!/usr/bin/env python3
"""
flatten.py — Inline all \\input{} directives in a LaTeX file to produce
a single flat .tex file suitable for PLOS submission.

Usage:
    python3 flatten.py manuscript.tex                  # -> manuscript_flat.tex
    python3 flatten.py manuscript.tex -o submission.tex
    python3 flatten.py supplement_main.tex -o supplement_flat.tex
"""

import re
import sys
import argparse
from pathlib import Path


def resolve_input_path(input_arg: str, current_dir: Path, root_dir: Path) -> Path:
    """
    Resolve an \\input{arg} to a real file path.
    LaTeX searches relative to the current file first, then the root dir.
    Adds .tex extension if missing.
    """
    p = Path(input_arg)
    if not p.suffix:
        p = p.with_suffix(".tex")

    # Try relative to the file that contains the \input
    candidate = current_dir / p
    if candidate.exists():
        return candidate.resolve()

    # Try relative to the root directory
    candidate = root_dir / p
    if candidate.exists():
        return candidate.resolve()

    raise FileNotFoundError(
        f"Cannot find \\input{{{input_arg}}} "
        f"(searched in {current_dir} and {root_dir})"
    )


def flatten(file_path: Path, root_dir: Path, visited: set[Path]) -> str:
    """
    Recursively read file_path and replace every \\input{...} line
    with the contents of the referenced file.
    """
    file_path = file_path.resolve()

    if file_path in visited:
        print(f"  [warning] Circular \\input detected, skipping: {file_path}", file=sys.stderr)
        return ""
    visited.add(file_path)

    print(f"  Reading: {file_path.relative_to(root_dir)}", file=sys.stderr)
    text = file_path.read_text(encoding="utf-8")

    current_dir = file_path.parent

    # Match \input{...} — not preceded by % (i.e. not commented out)
    # Also handles optional whitespace around the braces
    input_pattern = re.compile(
        r'^(?P<indent>[^\S\n]*)(?P<cmd>\\input\s*\{(?P<arg>[^}]+)\})',
        re.MULTILINE,
    )

    def replace_input(match):
        full_line = match.group(0)
        indent = match.group("indent")
        arg = match.group("arg").strip()

        # Check if the \input is on a commented-out line
        # (look back to the start of the line for a %)
        line_start = match.string.rfind('\n', 0, match.start()) + 1
        line_before_match = match.string[line_start:match.start()]
        if '%' in line_before_match:
            return full_line  # leave commented-out inputs alone

        try:
            target = resolve_input_path(arg, current_dir, root_dir)
        except FileNotFoundError as e:
            print(f"  [warning] {e}", file=sys.stderr)
            return full_line  # leave unresolved inputs as-is

        separator = f"\n% --- begin input: {arg} ---\n"
        end_sep   = f"\n% --- end input:   {arg} ---\n"
        inlined = flatten(target, root_dir, visited)

        # Re-indent only if the \input itself was indented
        if indent:
            inlined = "\n".join(indent + line if line.strip() else line
                                for line in inlined.splitlines())

        return separator + inlined + end_sep

    return input_pattern.sub(replace_input, text)


def main():
    parser = argparse.ArgumentParser(
        description="Flatten a multi-file LaTeX project into a single .tex file."
    )
    parser.add_argument(
        "input",
        help="Root .tex file (e.g. manuscript.tex)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Output file path. Defaults to <stem>_flat.tex next to the input file.",
    )
    parser.add_argument(
        "--root",
        help="Root directory for resolving \\input paths. Defaults to the directory of the input file.",
    )
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    if not input_path.exists():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    root_dir = Path(args.root).resolve() if args.root else input_path.parent

    if args.output:
        output_path = Path(args.output).resolve()
    else:
        output_path = input_path.parent / (input_path.stem + "_flat.tex")

    print(f"Flattening: {input_path}", file=sys.stderr)
    print(f"Root dir:   {root_dir}", file=sys.stderr)
    print(f"Output:     {output_path}", file=sys.stderr)
    print(file=sys.stderr)

    result = flatten(input_path, root_dir, visited=set())

    header = (
        "% This file was automatically generated by flatten.py\n"
        f"% Source: {input_path.name}\n"
        "% Do not edit this file directly — edit the source files instead.\n"
        "% ---------------------------------------------------------------\n\n"
    )

    output_path.write_text(header + result, encoding="utf-8")
    print(f"\nDone. Flat file written to: {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
